### ISSUE TITLE
make the time the server waits before kicking someone from a multiplayer game configurable

### ISSUE THREAD

**Issue by soundmud** [soundmud/soundrts#87]
For example: the parameter would be in the config file, named auto_disconnect_delay_in_seconds with a default of 60 seconds.

**Comment by soundmud** [comment]
The best solution (make sure that the other players agree) is probably too tedious to be ready for alpha 11.
I have created a separate issue for it: issue #92

**Comment by thgcode** [comment]
I have implemented on my fork of SoundRTS the solution described in this issue (configure the timeout in the soundrts.ini file).
We'll need to think in a way to fix the other issue, because spawning menus inside the game itself locks the interface.
In my pull request (which includes all the changes I have made) I fixed the tiping part of the bug, but I think that's not enough to fix it on the menus.

**Comment by soundmud** [comment]
Perfect, thanks!
I have added issue #93 as a prerequisite of issue #92.

**Comment by soundmud** [comment]
This parameter will still be useful. Instead of being the automatic disconnect delay, it will be the delay before manual disconnection appears in the menus.
